AWSTemplateFormatVersion: '2010-09-09'
Description: ASG Demo Min/MaxCount 1 (default)

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Network Configuration"
        Parameters:
          - TargetVPC
          - TargetSubnetA
          - TargetSubnetB
      -
        Label:
          default: "Security Group Configuration"
        Parameters:
          - SecurityGroup1
          - SecurityGroup2
          - SecurityGroup3
          - SecurityGroup4
          - SecurityGroup5
      -
        Label:
          default: "EC2 Configuration"
        Parameters:
          - KeyName
          - InstanceType
          - InstanceImageId
          - InstanceCount
          - InstanceCountMin
          - InstanceCountMax

    ParameterLabels:
      VPCID:
        default: "Which VPC should this be deployed to?"

Parameters:

  TargetVPC:
    ConstraintDescription: Select VPC Id/Name
    Type: AWS::EC2::VPC::Id
  TargetSubnetA:
    Description: Select Subnet Id/Name
    Type: AWS::EC2::Subnet::Id
  TargetSubnetB:
    Description: Select Subnet Id/Name
    Type: AWS::EC2::Subnet::Id
  SecurityGroup1:
    Description: ALB Security group 1 (type ahead to filter group list)
    Type: AWS::EC2::SecurityGroup::Id
  SecurityGroup2:
    Description: ALB Security group 2 (type ahead to filter group list)
    Type: AWS::EC2::SecurityGroup::Id
  SecurityGroup3:
    Description: ALB Security group 3 (type ahead to filter group list)
    Type: AWS::EC2::SecurityGroup::Id
  SecurityGroup4:
    Description: ALB Security group 4 (type ahead to filter group list)
    Type: AWS::EC2::SecurityGroup::Id
  SecurityGroup5:
    Description: ALB Security group 5 (type ahead to filter group list)
    Type: AWS::EC2::SecurityGroup::Id

  InstanceType:
    Description: Select EC2 instance type (Limited Selection)
    Type: String
    Default: t2.nano
    AllowedValues:
    - t2.nano
    - t2.micro
  InstanceImageId:
    Description: Imput AMI Id
    Default: ami-e92fec90
    Type: String
  KeyName:
    Description: Select EC2 KeyPair
    Type: AWS::EC2::KeyPair::KeyName
  InstanceCount:
    Description: Number of EC2 instances to launch
    Type: Number
    Default: 1
    MaxValue: 5
  InstanceCountMin:
    Description: Maximum number of EC2 instances to launch
    Type: Number
    Default: 1
    MaxValue: 1
  InstanceCountMax:
    Description: Maximum number of EC2 instances to launch
    Type: Number
    Default: 1
    MaxValue: 5

Resources:
  AppServerGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - !Ref TargetSubnetA
        - !Ref TargetSubnetB
      LaunchConfigurationName: !Ref  AppLaunchConfig
      DesiredCapacity: !Ref  InstanceCount
      MinSize: !Ref InstanceCountMin
      MaxSize: !Ref InstanceCountMax
      LoadBalancerNames:
        - !Ref AppLoadBalancer
      HealthCheckGracePeriod: '300'
      HealthCheckType: ELB
    CreationPolicy:
      ResourceSignal:
        Count: !Ref InstanceCount
        Timeout: PT5M
    UpdatePolicy:
      AutoScalingReplacingUpdate:
        WillReplace: 'true'

  AppLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      AssociatePublicIpAddress: 'true'
      ImageId: !Ref InstanceImageId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      # UserData:

  AppLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internal
      Subnets:
        - !Ref TargetSubnetA
        - !Ref TargetSubnetB
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: '50'
      SecurityGroups:
        - !Ref SecurityGroup1
        - !Ref SecurityGroup2
        - !Ref SecurityGroup3
        - !Ref SecurityGroup4
        - !Ref SecurityGroup5
      Tags:
      - Key: key
        Value: value
      - Key: key2
        Value: value2

Outputs:
  AccouuntId:
    Description: Stack Deployed in Account
    Value: AWS::AccountId
  StackId:
    Description: Stack Id
    Value: AWS::StackId
  StackName:
    Description: Stack Name
    Value: AWS:StackName
  DeployedRegion:
    Description: Stack Deployed in Region
    Value: AWS::Region